name: Lint Code

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        npm install -g stylelint htmlhint eslint
    - name: Run stylelint
      run: stylelint "**/*.css"
    - name: Run htmlhint
      run: htmlhint "**/*.html"
    - name: Run eslint
      run: eslint "**/*.js"
